name: waitapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter_modular: ^5.0.3
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  cloud_firestore: ^5.6.5
  sleek_circular_slider: ^2.0.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/icon.png"

flutter:
  uses-material-design: true

assets:
  - assets/
  - images/