// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLmu3-gbr67ltWUnM0k0KE5vc6TWroEZU',
    appId: '1:971966930729:web:c0dc8c3f98e43383072138',
    messagingSenderId: '971966930729',
    projectId: 'kadore-e-pagers',
    authDomain: 'kadore-e-pagers.firebaseapp.com',
    databaseURL: 'https://kadore-e-pagers-default-rtdb.firebaseio.com',
    storageBucket: 'kadore-e-pagers.firebasestorage.app',
    measurementId: 'G-6893KYR1LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2BqYMB8LhCeesD-4zk71aK3euZP4_uY',
    appId: '1:971966930729:android:4a7f6f0b78e82460072138',
    messagingSenderId: '971966930729',
    projectId: 'kadore-e-pagers',
    databaseURL: 'https://kadore-e-pagers-default-rtdb.firebaseio.com',
    storageBucket: 'kadore-e-pagers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzsJFHlFOY6NQCv9qVx1bEzw_0JkeeMc',
    appId: '1:971966930729:ios:6c91d1c7b7b20b91072138',
    messagingSenderId: '971966930729',
    projectId: 'kadore-e-pagers',
    databaseURL: 'https://kadore-e-pagers-default-rtdb.firebaseio.com',
    storageBucket: 'kadore-e-pagers.firebasestorage.app',
    iosBundleId: 'com.example.waitapp',
  );
}
